name: zadanie 1 2

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  

jobs:
  buildx:
    name: Wykonanie zadania 1 i 2
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
        
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
              username: ${{ secrets.DOCKER_HUB_USER }}
              password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Run Buildx Single Arch
        run: |
          docker buildx build \
            --output "type=image,push=true" \
            --tag beyondoblivion/project2:zadanie1 \
            --file ./dockerfile.v1  ./ 
            
      -
        name: Run Buildx Multi Arch
        run: |
          docker buildx build \
            --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7 \
            --output "type=image,push=true" \
            --tag beyondoblivion/project2:zadanie2 \
            --file ./dockerfile.v1  ./
            
